pipeline:
  name: snyk original scan
  identifier: snyk_original_scan
  tags: {}
  projectIdentifier: juiceShop_bm
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: final_js_bm
        build: <+input>
  stages:
    - stage:
        name: init
        identifier: init
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.remediationagentdelegate
              namespace: harness-qa-delegate
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: install_deps
                  spec:
                    connectorRef: account.harnessImage
                    image: node:22
                    shell: Sh
                    command: |
                      rm -f frontend/package-lock.json
                      npm install
                    resources:
                      limits:
                        memory: 4Gi
                        cpu: "2"
              - step:
                  type: Snyk
                  name: Snyk_1
                  identifier: Snyk_1
                  spec:
                    mode: orchestration
                    config: oss
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    privileged: true
                    auth:
                      access_token: snyk_uat.1fcad39e.eyJlIjoxNzk3NzU0NDEyLCJoIjoic255ay5pbyIsImoiOiJBYUREQnp2QTFfOHFuT2F2eDYtTFhnIiwicyI6Im41MkNYMzVfU2Jpb0N5ci1hckk5TUEiLCJ0aWQiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFBIn0.rJTmofhIdS3x-C_CEl5-V5zv0wVlHrAmouKu4Aogn3NE-WCdvJTkmL4mpFUMwlWccEtyOnhj39t03r41VqlUCw
                    sbom:
                      format: spdx-json
